### ISSUE TITLE
Does not perform well in Firefox

### ISSUE THREAD

**Issue by rofrol** [brandly/elm-flame-graph#4]

**Comment by brandly** [comment]
hm, yeah. is there any console output or anything? it completely crashed firefox on my end lol

i feel like i was primarily using firefox when i made this, so i'm not sure what has changed.

**Comment by brandly** [comment]
just updated to firefox 69, and it was working!

<img width="1552" alt="Screen Shot 2019-09-03 at 12 02 22 PM" src="https://user-images.githubusercontent.com/820696/64189733-df3d2300-ce42-11e9-95e5-4712a358b7a8.png">

sort of... i tried resizing the page for a smaller screenshot, and it made the browser mostly unresponsive. i can open a new tab, but it won't actually navigate to a URL.

<img width="716" alt="Screen Shot 2019-09-03 at 12 07 15 PM" src="https://user-images.githubusercontent.com/820696/64189989-65f20000-ce43-11e9-95f9-708264707df2.png">

chrome/safari handle it just fine. interesting stuff.

i can't seem to get access to dev tools, so i'm not sure how to diagnose what's going on. firefox has a process consuming 99% cpu. 

is the elm itself behaving differently in firefox? seems unlikely. the file parsing is pretty messy, but since it has rendered a flame graph, the parsing has to work.

is the recursive nature of the styles, while [exclusively using inline styles](https://github.com/brandly/elm-flame-graph/blob/c599aa291a0405ac9947726233962f2b9eb9bdcb/src/FlameGraph.elm#L77-L105), pushing FF's layout engine to its limits? i guess it could. moving to class names and static css would be a good experiment.

**Comment by rofrol** [comment]
Works in Firefox 69.

**Comment by brandly** [comment]
it kinda works on my end, but opening dev tools and expanding that pane seems to crash my browser. gonna leave this open, cause maybe i'll dig in and figure out why chrome/safari is outperforming FF by such a wide margin.

**Comment by brandly** [comment]
Firefox 70 rendered the page initially but still crashed when i resized the window...

**Comment by brandly** [comment]
Haven’t tried yet, but looks like we can dig into the browser’s performance https://twitter.com/vjeux/status/1221562363624771584

**Comment by brandly** [comment]
@rofrol are you using this project for anything? I’m just curious

**Comment by rofrol** [comment]
No

**Comment by brandly** [comment]
firefox 85 appears to handle this just fine lol. @rofrol want to confirm and close this?

**Comment by rofrol** [comment]
Works ok on Firefox for Android.
